version: "3"
services:
  node:
    container_name: node
    image: gcr.io/gochain-core/gochain:${GOCHAIN_TAG:-stable}
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - .:/gochain
    command: gochain --config /gochain/config.toml --datadir /gochain/node --cache ${GOCHAIN_CACHE:-4096} --rpc --mine --unlock ${GOCHAIN_ACCT} --password /gochain/password.txt --netstats ${NETSTATS_NAME}:${NETSTATS_SECRET}@159.65.255.3 --miner.extradata ${GOCHAIN_EXTRADATA}
    restart: always
