version: "3"
services:
  node:
    container_name: node
    image: gochain/gochain:${GOCHAIN_TAG:-testnet}
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - .:/gochain
    command: gochain --testnet --datadir /gochain/node --cache ${GOCHAIN_CACHE:-4096} --rpc
    restart: always
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
