version: "3"
services:
  node:
    container_name: node
    image: gochain/gochain:${GOCHAIN_TAG:-stable}
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - .:/gochain
    command: gochain --networkID ${GOCHAIN_NETWORK} --config /gochain/config.toml --nodiscover --datadir /gochain/node --cache ${GOCHAIN_CACHE:-1024} --rpc --mine --unlock ${GOCHAIN_ACCT}
    restart: always
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
