version: "3"
services:
  node:
    container_name: node
    image: gochain/gochain:${TAG:-latest}
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      # dd-agent
      - "8125:8125/udp"
    volumes:
      - .:/gochain
    command: gochain --cache ${CACHE:-4096} --rpc --mine --unlock ${ACCT:?err} --password /gochain/password.txt
  netintel:
    container_name: netintel
    image: gochain/net-intelligence-api:latest
    depends_on:
      - node
    network_mode: "service:node"
    volumes:
      - ./app.json:/home/netintel/app.json
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
