version: "3"
services:
  node:
    container_name: node
    image: gcr.io/gochain-core/gochain:${GOCHAIN_TAG:-stable}
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - .:/gochain
    command: gochain --datadir /gochain/node --cache ${GOCHAIN_CACHE:-4096} --rpc
    restart: always
